[project]
name = "my-speaking-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sjfh12345", email = "sjfh12345@naver.com" }
]
requires-python = ">=3.11"
dependencies = [
    "bcrypt>=5.0.0",
    "fastapi[standard]>=0.142.2",
    "httpx>=0.28.1",
    "passlib>=1.7.4",
    "psycopg[binary]>=3.3.6",
    "pyjwt>=2.15.1",
    "python-dotenv>=1.2.4",
]

[project.scripts]
my-speaking-ai = "my_speaking_ai:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
